### ISSUE TITLE
Preinstall.sh not working with macos

### ISSUE THREAD

**Issue by roine** [sfast/zeronode#66]
Issue
==
This command is executed at the end of the preinstall.sh script.
```shell
$packageManager install -y $libzmq
```
`-y` is not a valid brew option, see thorwn error message:

> Error: invalid option: -y

Potential Solution
==
If -y in other OS library manager means say yes to all questions, then it could be replaced by `yes`, eg:
```shell
yes | $packageManager install $libzmq
```

Need to check support first.

**Comment by artakvg** [comment]
Fixed in newer version
